version:  '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
        POSTGRES_USER: ashik
        POSTGRES_PASSWORD: 123
        POSTGRES_DB: site_managements
    networks:
      - freecodecamp
networks:
  freecodecamp:
    